# Change this to your own config
#---------------------------------------------------#
## Updated: 2025-11-18 03:49:14
#---------------------------------------------------#

mixed-port: 7890
allow-lan: true

mode: rule

log-level: info

external-controller: 127.0.0.1:39597

dns:
  enable: true
  nameserver:

proxies:
proxy-groups:
    - { name: 'Best_VPN', type: fallback, proxies: ['SG','US','HK'] , interval: 900 }

rules:
    - 'MATCH,Best_VPN'
